const storeDemoData =
{
  initialSelectedIndex: 0,
  title: '',
  corpId: null,
  appId: null,
  appName: '',
  solutionCode: null,
  todos: 0,
  UserInfo: { departmentName: '', dingtalkAccount: '' },
  homeData: {
    Apps: [], ReportWidgets: [], RecentModule: [], TotalWorkflows: 0,
  },
  groupMenus: [],
  expired: false,
  willExpired: false,
  expireDate: '2017-08-30',
  boCountExceed: false,
  boCountWillExceed: false,
  fileSizeExceed: false,
  fileSizeWillExceed: false,
  monthlyBoCount: 0,
  totalBoCount: 0,
  monthlyFileSizeCount: 0,
  totalFileSize: 0,
  formData: {
    data: {
      ObjectId: {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '2952b087-d820-49ce-99e0-5261ca60dc68', DisplayName: 'ObjectId', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      Name: {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '    ', DisplayName: '数据标题', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      CreatedBy: {
        Type: 26,
        Visible: true,
        Editable: false,
        Required: false,
        Printable: true,
        Value: [{
          UnitType: 4, FullName: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: '', Title: '', HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DepartmentName: '前端开发', Password: null, Mobile: '15999606649', Email: null, DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', DingId: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', WeChatUserId: null, Position: null, ExtAttr: '{}', ViceParentIds: ['b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentIds: ['4b87d361-d7df-40b6-bbaf-e0c1b065c190', 'b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentId: '4b87d361-d7df-40b6-bbaf-e0c1b065c190', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '周娅琴', Description: null, UnitId: 'fed446bc-0369-4da0-8fe1-a869d1375049', Code: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', ManagerId: null, CreatedTime: '/Date(1528423937000)/', ModifiedTime: '/Date(1539164182000)/', SortKey: 0, Serialized: true, ObjectId: 'fed446bc-0369-4da0-8fe1-a869d1375049', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
        }],
        DisplayName: '创建人',
        DataDictItemValue: null,
        ComputationRuleFields: null,
        ComputationRule: null,
        DisplayRuleFields: null,
        DisplayRule: null,
      },
      OwnerId: {
        Type: 26,
        Visible: true,
        Editable: false,
        Required: false,
        Printable: true,
        Value: [{
          UnitType: 4, FullName: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: '', Title: '', HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DepartmentName: '前端开发', Password: null, Mobile: '15999606649', Email: null, DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', DingId: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', WeChatUserId: null, Position: null, ExtAttr: '{}', ViceParentIds: ['b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentIds: ['4b87d361-d7df-40b6-bbaf-e0c1b065c190', 'b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentId: '4b87d361-d7df-40b6-bbaf-e0c1b065c190', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '周娅琴', Description: null, UnitId: 'fed446bc-0369-4da0-8fe1-a869d1375049', Code: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', ManagerId: null, CreatedTime: '/Date(1528423937000)/', ModifiedTime: '/Date(1539164182000)/', SortKey: 0, Serialized: true, ObjectId: 'fed446bc-0369-4da0-8fe1-a869d1375049', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
        }],
        DisplayName: '拥有者',
        DataDictItemValue: null,
        ComputationRuleFields: null,
        ComputationRule: null,
        DisplayRuleFields: null,
        DisplayRule: null,
      },
      OwnerDeptId: {
        Type: 26,
        Visible: true,
        Editable: false,
        Required: false,
        Printable: true,
        Value: [{
          UnitType: 2, DingTalkDepartmentId: 67343742, WeChatDepartmentId: null, ParentId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '研发中心', Description: null, UnitId: '29169d71-7286-45b1-a433-fed0eda05524', Code: '29169d71-7286-45b1-a433-fed0eda05524', ManagerId: '8d1150d5-79ab-40ef-b88e-1c8ed191c454', CreatedTime: '/Date(1528357345000)/', ModifiedTime: '/Date(1535944188000)/', SortKey: 0, Serialized: true, ObjectId: '29169d71-7286-45b1-a433-fed0eda05524', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
        }],
        DisplayName: '所属部门',
        DataDictItemValue: null,
        ComputationRuleFields: null,
        ComputationRule: null,
        DisplayRuleFields: null,
        DisplayRule: null,
      },
      CreatedTime: {
        Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-07-11 22:25:21', DisplayName: '创建时间', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      ModifiedBy: {
        Type: 26,
        Visible: true,
        Editable: false,
        Required: false,
        Printable: true,
        Value: [{
          UnitType: 4, FullName: 'System[System]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: null, Title: null, HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: null, DepartmentName: '氚云检测（V1+Swork+Odesy）', Password: null, Mobile: null, Email: null, DingTalkAccount: null, DingId: null, WeChatUserId: null, Position: null, ExtAttr: null, ViceParentIds: [], ParentIds: ['18f923a7-5a5e-426d-94ae-a55ad1a4b240'], ParentId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: 'System', Description: null, UnitId: '18f923a7-5a5e-426d-94ae-a55ad1a4b239', Code: 'System', ManagerId: null, CreatedTime: '/Date(1528356132000)/', ModifiedTime: '/Date(1528356132000)/', SortKey: 0, Serialized: true, ObjectId: '18f923a7-5a5e-426d-94ae-a55ad1a4b239', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
        }],
        DisplayName: 'ModifiedBy',
        DataDictItemValue: null,
        ComputationRuleFields: null,
        ComputationRule: null,
        DisplayRuleFields: null,
        DisplayRule: null,
      },
      ModifiedTime: {
        Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-11-08 16:30:50', DisplayName: '修改时间', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      WorkflowInstanceId: {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '6848aa5e-f031-4bb3-8d87-2ac61205a149', DisplayName: 'WorkflowInstanceId', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      Status: {
        Type: 9, Visible: true, Editable: false, Required: false, Printable: true, Value: 1, DisplayName: 'Status', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      F0000005: {
        Type: 7, Visible: true, Editable: false, Required: false, Printable: true, Value: '', DisplayName: '数字', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null, dataField: 'F0000005', controlkey: 'FormNumber', displayname: '数字', description: '', decimalplaces: '', showmode: '0', sourcetype: null,
      },
      F0000002: {
        Type: 23,
        Visible: true,
        Editable: false,
        Required: false,
        Printable: true,
        Value: [{
          Code: '537f2de9-6585-4fff-ba40-d6d477e6ce16', Name: 'image.jpg', Description: null, Url: '/Form/Download/?AttachmentID=537f2de9-6585-4fff-ba40-d6d477e6ce16', ThumbnailUrl: 'https://testci-ossthumbnail.oss-cn-shenzhen.aliyuncs.com/t0pyfnw9k53ocwir4tkbav932/537f2de9-6585-4fff-ba40-d6d477e6ce16', Size: 1908141, SortKey: 1,
        }],
        DisplayName: '图片',
        DataDictItemValue: null,
        ComputationRuleFields: null,
        ComputationRule: null,
        DisplayRuleFields: null,
        DisplayRule: null,
        dataField: 'F0000002',
        controlkey: 'FormPhoto',
        displayname: '图片',
        description: null,
        uploadmultiple: 'false',
        sourcetype: null,
        cameraonly: 'false',
        hasWaterMark: 'false',
        compression: 'false',
      },
      F0000006: {
        Type: 23, Visible: true, Editable: false, Required: false, Printable: true, Value: [], DisplayName: '图片多张', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: ['F0000007'], DisplayRule: '$.fn.ISNULL({F0000007})', dataField: 'F0000006', controlkey: 'FormPhoto', displayname: '图片多张', description: null, uploadmultiple: 'true', sourcetype: null, cameraonly: 'false', hasWaterMark: 'false', compression: 'false',
      },
      F0000007: {
        Type: 56, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '地址', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null, dataField: 'F0000007', controlkey: 'FormAreaSelect', displayname: '地址', description: null, areamode: 'P-C-T', showdetailaddr: 'true', sourcetype: null,
      },
      'CreatedBy.FullName': {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴', DisplayName: 'CreatedBy.FullName', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      ActivityCode: {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: 'Activity3', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      InstanceId: {
        Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '6848aa5e-f031-4bb3-8d87-2ac61205a149', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      InstanceName: {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '    ', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      OriginateDate: {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018/7/11', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      OriginateFullTime: {
        Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-07-11 22:25:22', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      OriginateTime: {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '22:25', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      Originator: {
        Type: 26, Visible: true, Editable: false, Required: false, Printable: true, Value: 'fed446bc-0369-4da0-8fe1-a869d1375049', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.FullName': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.LoginName': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.UserName': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.UserID': {
        Type: 26, Visible: true, Editable: false, Required: false, Printable: true, Value: 'fed446bc-0369-4da0-8fe1-a869d1375049', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.Mobile': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '15999606649', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.OUName': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.OUFullName': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '/前端开发', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
      'Originator.OU': {
        Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
      },
    },
    pageId: 'D000130kk889',
    responseContext: {
      WorkflowState: 4,
      InstanceApproval: 1,
      ActivityCode: 'Activity3',
      DisplayName: '图片控件',
      SchemaCode: 'D000130kk889',
      Originator: 'fed446bc-0369-4da0-8fe1-a869d1375049',
      OriginatorCode: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==',
      OriginatorParentId: '4b87d361-d7df-40b6-bbaf-e0c1b065c190',
      WorkflowVersion: 5,
      FormMode: 1,
      IsCreateMode: false,
      InstanceId: '6848aa5e-f031-4bb3-8d87-2ac61205a149',
      BizObjectId: '2952b087-d820-49ce-99e0-5261ca60dc68',
      BizObjectStatus: 1,
      WorkItemId: '68ee5731-2be0-485b-a811-665e7985f577',
      Close: false,
      WorkItemType: 2,
      Actions: {
        Remove: {
          Action: 'Remove', Icon: 'fa-minus', Text: '删除', IsPrintAction: false, PrintTemplateCode: null,
        },
      },
      AssociatedBoNames: {},
      AssociationLists: {},
      EnableFormSns: false,
      EnableTask: false,
      Name: '    ',
      FormDataType: 1,
      ReturnData: {
        ObjectId: {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '2952b087-d820-49ce-99e0-5261ca60dc68', DisplayName: 'ObjectId', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        Name: {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '    ', DisplayName: '数据标题', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        CreatedBy: {
          Type: 26,
          Visible: true,
          Editable: false,
          Required: false,
          Printable: true,
          Value: [{
            UnitType: 4, FullName: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: '', Title: '', HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DepartmentName: '前端开发', Password: null, Mobile: '15999606649', Email: null, DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', DingId: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', WeChatUserId: null, Position: null, ExtAttr: '{}', ViceParentIds: ['b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentIds: ['4b87d361-d7df-40b6-bbaf-e0c1b065c190', 'b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentId: '4b87d361-d7df-40b6-bbaf-e0c1b065c190', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '周娅琴', Description: null, UnitId: 'fed446bc-0369-4da0-8fe1-a869d1375049', Code: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', ManagerId: null, CreatedTime: '/Date(1528423937000)/', ModifiedTime: '/Date(1539164182000)/', SortKey: 0, Serialized: true, ObjectId: 'fed446bc-0369-4da0-8fe1-a869d1375049', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
          }],
          DisplayName: '创建人',
          DataDictItemValue: null,
          ComputationRuleFields: null,
          ComputationRule: null,
          DisplayRuleFields: null,
          DisplayRule: null,
        },
        OwnerId: {
          Type: 26,
          Visible: true,
          Editable: false,
          Required: false,
          Printable: true,
          Value: [{
            UnitType: 4, FullName: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: '', Title: '', HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DepartmentName: '前端开发', Password: null, Mobile: '15999606649', Email: null, DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', DingId: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', WeChatUserId: null, Position: null, ExtAttr: '{}', ViceParentIds: ['b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentIds: ['4b87d361-d7df-40b6-bbaf-e0c1b065c190', 'b57d08a8-a5db-4e53-bae1-e43d5fbb8794'], ParentId: '4b87d361-d7df-40b6-bbaf-e0c1b065c190', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '周娅琴', Description: null, UnitId: 'fed446bc-0369-4da0-8fe1-a869d1375049', Code: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', ManagerId: null, CreatedTime: '/Date(1528423937000)/', ModifiedTime: '/Date(1539164182000)/', SortKey: 0, Serialized: true, ObjectId: 'fed446bc-0369-4da0-8fe1-a869d1375049', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
          }],
          DisplayName: '拥有者',
          DataDictItemValue: null,
          ComputationRuleFields: null,
          ComputationRule: null,
          DisplayRuleFields: null,
          DisplayRule: null,
        },
        OwnerDeptId: {
          Type: 26,
          Visible: true,
          Editable: false,
          Required: false,
          Printable: true,
          Value: [{
            UnitType: 2, DingTalkDepartmentId: 67343742, WeChatDepartmentId: null, ParentId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: '研发中心', Description: null, UnitId: '29169d71-7286-45b1-a433-fed0eda05524', Code: '29169d71-7286-45b1-a433-fed0eda05524', ManagerId: '8d1150d5-79ab-40ef-b88e-1c8ed191c454', CreatedTime: '/Date(1528357345000)/', ModifiedTime: '/Date(1535944188000)/', SortKey: 0, Serialized: true, ObjectId: '29169d71-7286-45b1-a433-fed0eda05524', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
          }],
          DisplayName: '所属部门',
          DataDictItemValue: null,
          ComputationRuleFields: null,
          ComputationRule: null,
          DisplayRuleFields: null,
          DisplayRule: null,
        },
        CreatedTime: {
          Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-07-11 22:25:21', DisplayName: '创建时间', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        ModifiedBy: {
          Type: 26,
          Visible: true,
          Editable: false,
          Required: false,
          Printable: true,
          Value: [{
            UnitType: 4, FullName: 'System[System]', Birthday: '/Date(-6847833600000)/', Gender: 0, EntryDate: '/Date(-6847833600000)/', DepartureDate: '/Date(-6847833600000)/', EmployeeNumber: null, Title: null, HomePhone: null, OfficePhone: null, QQ: null, IdNumber: null, EmployeeRank: 0, ProfilePhotoUrl: null, DepartmentName: '氚云检测（V1+Swork+Odesy）', Password: null, Mobile: null, Email: null, DingTalkAccount: null, DingId: null, WeChatUserId: null, Position: null, ExtAttr: null, ViceParentIds: [], ParentIds: ['18f923a7-5a5e-426d-94ae-a55ad1a4b240'], ParentId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', CompanyId: '18f923a7-5a5e-426d-94ae-a55ad1a4b240', Visibility: 7, State: 0, DomainType: 1, Name: 'System', Description: null, UnitId: '18f923a7-5a5e-426d-94ae-a55ad1a4b239', Code: 'System', ManagerId: null, CreatedTime: '/Date(1528356132000)/', ModifiedTime: '/Date(1528356132000)/', SortKey: 0, Serialized: true, ObjectId: '18f923a7-5a5e-426d-94ae-a55ad1a4b239', ParentObjectId: '', ParentPropertyName: null, ParentIndex: 0, DirtyProperties: [],
          }],
          DisplayName: 'ModifiedBy',
          DataDictItemValue: null,
          ComputationRuleFields: null,
          ComputationRule: null,
          DisplayRuleFields: null,
          DisplayRule: null,
        },
        ModifiedTime: {
          Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-11-08 16:30:50', DisplayName: '修改时间', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        WorkflowInstanceId: {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '6848aa5e-f031-4bb3-8d87-2ac61205a149', DisplayName: 'WorkflowInstanceId', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        Status: {
          Type: 9, Visible: true, Editable: false, Required: false, Printable: true, Value: 1, DisplayName: 'Status', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        F0000005: {
          Type: 7, Visible: true, Editable: false, Required: false, Printable: true, Value: '', DisplayName: '数字', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null, dataField: 'F0000005', controlkey: 'FormNumber', displayname: '数字', description: '', decimalplaces: '', showmode: '0', sourcetype: null,
        },
        F0000002: {
          Type: 23,
          Visible: true,
          Editable: false,
          Required: false,
          Printable: true,
          Value: [{
            Code: '537f2de9-6585-4fff-ba40-d6d477e6ce16', Name: 'image.jpg', Description: null, Url: '/Form/Download/?AttachmentID=537f2de9-6585-4fff-ba40-d6d477e6ce16', ThumbnailUrl: 'https://testci-ossthumbnail.oss-cn-shenzhen.aliyuncs.com/t0pyfnw9k53ocwir4tkbav932/537f2de9-6585-4fff-ba40-d6d477e6ce16', Size: 1908141, SortKey: 1,
          }],
          DisplayName: '图片',
          DataDictItemValue: null,
          ComputationRuleFields: null,
          ComputationRule: null,
          DisplayRuleFields: null,
          DisplayRule: null,
          dataField: 'F0000002',
          controlkey: 'FormPhoto',
          displayname: '图片',
          description: null,
          uploadmultiple: 'false',
          sourcetype: null,
          cameraonly: 'false',
          hasWaterMark: 'false',
          compression: 'false',
        },
        F0000006: {
          Type: 23, Visible: true, Editable: false, Required: false, Printable: true, Value: [], DisplayName: '图片多张', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: ['F0000007'], DisplayRule: '$.fn.ISNULL({F0000007})', dataField: 'F0000006', controlkey: 'FormPhoto', displayname: '图片多张', description: null, uploadmultiple: 'true', sourcetype: null, cameraonly: 'false', hasWaterMark: 'false', compression: 'false',
        },
        F0000007: {
          Type: 56, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '地址', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null, dataField: 'F0000007', controlkey: 'FormAreaSelect', displayname: '地址', description: null, areamode: 'P-C-T', showdetailaddr: 'true', sourcetype: null,
        },
        'CreatedBy.FullName': {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴', DisplayName: 'CreatedBy.FullName', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        ActivityCode: {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: 'Activity3', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        InstanceId: {
          Type: 14, Visible: true, Editable: false, Required: false, Printable: true, Value: '6848aa5e-f031-4bb3-8d87-2ac61205a149', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        InstanceName: {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '    ', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        OriginateDate: {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018/7/11', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        OriginateFullTime: {
          Type: 5, Visible: true, Editable: false, Required: false, Printable: true, Value: '2018-07-11 22:25:22', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        OriginateTime: {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '22:25', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        Originator: {
          Type: 26, Visible: true, Editable: false, Required: false, Printable: true, Value: 'fed446bc-0369-4da0-8fe1-a869d1375049', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.FullName': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴[$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==]', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.LoginName': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '$:LWCP_v1:$cg26+UuA8JvoXCawRWl+UQ==', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.UserName': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '周娅琴', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.UserID': {
          Type: 26, Visible: true, Editable: false, Required: false, Printable: true, Value: 'fed446bc-0369-4da0-8fe1-a869d1375049', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.Mobile': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '15999606649', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.OUName': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.OUFullName': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: '/前端开发', DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
        'Originator.OU': {
          Type: 13, Visible: true, Editable: false, Required: false, Printable: true, Value: null, DisplayName: '', DataDictItemValue: null, ComputationRuleFields: null, ComputationRule: null, DisplayRuleFields: null, DisplayRule: null,
        },
      },
      PrintConfig: {
        PrintCompanyName: true, PrintComment: true, Printer: true, PrintTime: true, PrintQrCode: true,
      },
      Comments: [{
        CommentId: '69266d3f-1dcb-4915-8bfc-16d577f3bdf3',
        UserProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg',
        DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f',
        UserParentName: '前端开发',
        UserName: '周娅琴',
        DelegantName: '',
        ActivityDisplayName: '审批节点',
        ModifiedTime: '/Date(1541665849000)/',
        Text: '同意',
        IsMyComment: true,
        Approval: true,
        TokenId: 2,
        Activity: 'Activity3',
        UserId: 'fed446bc-0369-4da0-8fe1-a869d1375049',
        Signature: null,
        Attachments: [{
          Code: 'c39182f6-d07e-4406-a0a2-3295d72c21ce', Name: '', Description: null, Url: '/Form/Download/?AttachmentID=c39182f6-d07e-4406-a0a2-3295d72c21ce', ThumbnailUrl: 'https://testci-ossthumbnail.oss-cn-shenzhen.aliyuncs.com/t0pyfnw9k53ocwir4tkbav932/c39182f6-d07e-4406-a0a2-3295d72c21ce', Size: 10682, SortKey: 0,
        }],
      }],
      WorkItems: [{
        WorkItemId: 'cd4f138e-b40c-4aad-ae30-5ab268f54d61', UserId: 'fed446bc-0369-4da0-8fe1-a869d1375049', UserProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', UserName: '周娅琴', ActivityDisplayName: '经办节点', State: 2, TokenId: 1, ActivityCode: 'Activity2', ReceiveTime: '2018/7/11 22:25:22', FinishTime: '2018/7/11 22:25:22', ItemType: 0, Approval: 1, Delegant: '',
      }, {
        WorkItemId: '68ee5731-2be0-485b-a811-665e7985f577', UserId: 'fed446bc-0369-4da0-8fe1-a869d1375049', UserProfilePhotoUrl: 'https://static.dingtalk.com/media/lADPDgQ9qSHCTtDNAmrNAn4_638_618.jpg', DingTalkAccount: '120024184921509431.ding83d0fc05f4b7420f35c2f4657eb6378f', UserName: '周娅琴', ActivityDisplayName: '审批节点', State: 2, TokenId: 2, ActivityCode: 'Activity3', ReceiveTime: '2018/7/11 22:25:22', FinishTime: '2018/11/8 16:30:49', ItemType: 2, Approval: 1, Delegant: '',
      }],
      RequestParameters: {
        SchemaCode: 'D000130kk889', BizObjectId: '2952b087-d820-49ce-99e0-5261ca60dc68', InstanceId: '6848aa5e-f031-4bb3-8d87-2ac61205a149', WorkflowVersion: '5', WorkItemId: '68ee5731-2be0-485b-a811-665e7985f577', Mode: 'View', IsExternalForm: 'False',
      },
      QrCodeUrl: 'https://swork.h3yun.com/mobile/?CorpId=ding83d0fc05f4b7420f35c2f4657eb6378f&sc=D000130kk889&bo=2952b087-d820-49ce-99e0-5261ca60dc68&mt=Task&IsIsv=1&sk=suitelg7ettn51zsfygkv',
      ReviewQrCodeUrl: 'https://swork.h3yun.com/FormExternal/ReviewQrCode/D000130kk889?EngineCode=t0pyfnw9k53ocwir4tkbav932',
      Successful: true,
      IsMobile: false,
      Message: '',
      Infos: [],
      IsExternalForm: false,
      ExternalFormUrl: null,
      RecentChange: { FormDataType: 1, FormMode: 4, SchemaDisplayName: '图片控件' },
      Errors: [],
      DebugTrack: null,
      ChangeSet: null,
    },
  },
  formRenderBol: false,
  FormMultiUserData: {
    OrgUnitItems: [], OrgTagItems: [], DepUserItems: {}, UserItems: [],
  },
  queryData: '',
  HasMore: true,
  querySelectedItems: [],
  reportFilters: {},
  curPost: null,
  childRenderedLen: 2,
  gridChildRenderedLen: {},
  gridChildLen: 0,
  excludeComp: [],
  IsExternalForm: null,
  suitekey: '',
  hostAddress: '',
  agentId: null,
  actionSuccess: false,
  taskPostBol: false,
  filterMarkObj: { mark: '', info: [] },
  gridChoosedDom: '',
  isGridOnChange: 0,
  rowId: '',
  isFormInitFinish: false,
  isGridFormInitFinish: false,
  AreaCotrolPopObj: { bol: false, keyName: '', ObjectId: '' },
  DateCotrolPopObj: { bol: false, keyName: '', ObjectId: '' },
  CotrolPopBol: false,
  breadListState: [],
  favoriteFunctions: [],
  isHtmlChangedBol: false,
  isGridPopupBol: false,
  engineCode: null,
  lastFilterBoxPosition: 0,
  isClickCustomButtom: false,
  attachmentPreviewShow: false,
  photoPreviewShow: false,
  isClickCommentButton: false,
  suiteKey: null,
  homeType: null,
};


export default storeDemoData;
